# Pandas

In [3]:
import pandas as pd

In [4]:
print(pd.__version__)

3.0.5

In [1]:
temps = [45, 98, 78, 67, 12]
print(temps)

[45, 98, 78, 67, 12]

In [5]:
data = {
    "ids" : ["A1", "A2", "A3", "B1"],
    "treatments" : ["Control", "Control", "Fertilizer", "Fertilizer"],
    "heights" : [12.4, 13.1, 15.8, 16.21]
}

In [6]:
df = pd.DataFrame(data)

In [7]:
df

  ids  treatments  heights
0  A1     Control    12.40
1  A2     Control    13.10
2  A3  Fertilizer    15.80
3  B1  Fertilizer    16.21

In [10]:
print(df.shape)

(4, 3)

In [11]:
print(df.columns)

Index(['ids', 'treatments', 'heights'], dtype='str')

In [12]:
print(list(df.columns))

['ids', 'treatments', 'heights']

In [14]:
heights = df["heights"] #Series

In [18]:
average_height = heights.mean()
print(f"Average Height: {average_height}")

Average Height: 14.3775

In [19]:
df.head()

  ids  treatments  heights
0  A1     Control    12.40
1  A2     Control    13.10
2  A3  Fertilizer    15.80
3  B1  Fertilizer    16.21

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ids         4 non-null      str
 1   treatments  4 non-null      str
 2   heights     4 non-null      float64
dtypes: float64(1), str(2)
memory usage: 228.0 bytes